services:
  maven:
    image: maven:3.8.6-jdk-8
    user: "$DEFAULT_DOCKER_USER"
    working_dir: /usr/src/maven
    volumes:
      - ./:/usr/src/maven
      - ../.git:/usr/src/.git:ro
      - ~/.m2:/var/maven/.m2
    environment:
      MAVEN_CONFIG: /var/maven/.m2
      GIT_DIR: /usr/src/.git
  node:
    image: "opendigitaleducation/node:16-alpine"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
      - ~/.npm:/.npm
      - ../recette:/home/node/recette
